name: Trader (Paper)

on:
  workflow_dispatch: {}
  push:
    paths:
      - "trading_script.py"
      - "requirements.txt"
      - ".github/workflows/trader.yml"
  # schedule:
  #   - cron: "32 13 * * 1-5"  # ex: 13:32 UTC jours ouvrés

permissions:
  contents: write

concurrency:
  group: trader-paper
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    env:
      TZ: America/New_York
      PYTHONUNBUFFERED: "1"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
      APCA_API_KEY_ID: ${{ secrets.ALPACA_API_KEY }}
      APCA_API_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
      APCA_API_BASE_URL: https://paper-api.alpaca.markets
      EXECUTE_PAPER: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure jq
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y >/dev/null 2>&1 || true
            sudo apt-get install -y jq >/dev/null 2>&1 || true
          fi

      - name: Quick diagnostics
        run: |
          echo "PWD: $(pwd)"
          ls -al
          python --version
          python - <<'PY'
          import sys, os
          print("sys.executable:", sys.executable)
          print("sys.path[0:3]:", sys.path[:3])
          f = "trading_script.py"
          print("trading_script.py exists:", os.path.exists(f))
          if os.path.exists(f):
              print("size(bytes):", os.path.getsize(f))
          PY

      - name: Sanity check Alpaca (Paper)
        run: |
          python - <<'PY'
          import os, json, urllib.request
          base = os.environ.get('APCA_API_BASE_URL', 'https://paper-api.alpaca.markets')
          req = urllib.request.Request(
              f"{base}/v2/account",
              headers={
                  "APCA-API-KEY-ID": os.environ["APCA_API_KEY_ID"],
                  "APCA-API-SECRET-KEY": os.environ["APCA_API_SECRET_KEY"],
              }
          )
          with urllib.request.urlopen(req, timeout=20) as r:
              data = json.loads(r.read().decode())
          subset = {k: data[k] for k in ("status","equity","cash","buying_power","pattern_day_trader","trading_blocked")}
          print(json.dumps(subset, indent=2))
          PY

      - name: Discover script CLI & logging hooks
        run: |
          set -Eeuo pipefail
          echo "--- DISCOVERY $(date -Is) ---" | tee run.log
          echo "---- trading_script.py --help ----" | tee -a run.log
          set +e
          python trading_script.py --help 2>&1 | tee -a run.log
          HELP_EXIT=${PIPESTATUS[0]}
          set -e
          echo "---- help exit=${HELP_EXIT} ----" | tee -a run.log

          echo "---- grep argparse ----" | tee -a run.log
          grep -nE 'ArgumentParser\(|add_argument\(' trading_script.py | head -n 80 | tee -a run.log || echo "(no argparse hits)" | tee -a run.log

          echo "---- grep logging ----" | tee -a run.log
          grep -nE 'import +logging|logging\.basicConfig|logging\.(info|debug|warning|error|critical)\(' trading_script.py | head -n 80 | tee -a run.log || echo "(no logging hits)" | tee -a run.log

          echo "---- grep Alpaca env usage ----" | tee -a run.log
          grep -nE 'APCA_|ALPACA_' trading_script.py | head -n 80 | tee -a run.log || echo "(no Alpaca env hits)" | tee -a run.log

      - name: Run trader (Paper) with logging injection
        run: |
          set -Eeuo pipefail
          echo "--- RUN $(date -Is) ---" | tee -a run.log
          PAPER_URL="https://paper-api.alpaca.markets"

          echo "---- Alpaca clock (paper) ----" | tee -a run.log
          curl -s \
            -H "APCA-API-KEY-ID: ${APCA_API_KEY_ID}" \
            -H "APCA-API-SECRET-KEY: ${APCA_API_SECRET_KEY}" \
            "${PAPER_URL}/v2/clock" \
            | jq -r '"is_open=\(.is_open) next_open=\(.next_open) next_close=\(.next_close)"' \
            | tee -a run.log || true

          echo "[RUN] Paper trading ON" | tee -a run.log
          export APCA_API_BASE_URL="${PAPER_URL}"

          # Injection logging + exécution du script en unbuffered
          set +e
          python -u - <<'PY' 2>&1 | tee -a run.log
          import os, sys, logging, runpy
          # Logging vers stdout (si le script ne configure rien, on a un fallback)
          logging.basicConfig(
              level=logging.INFO,
              format="%(asctime)s %(levelname)s %(name)s: %(message)s",
              stream=sys.stdout
          )
          os.environ.setdefault("APCA_API_BASE_URL", "https://paper-api.alpaca.markets")
          try:
              runpy.run_path("trading_script.py", run_name="__main__")
          except SystemExit as e:
              # Propager le code de sortie si le script appelle sys.exit()
              code = e.code if isinstance(e.code, int) else 0
              raise SystemExit(code)
          PY
          PY_EXIT=${PIPESTATUS[0]}
          set -e

          echo "---- python exit=${PY_EXIT} ----" | tee -a run.log

          echo "---- Collect local *.log (tail 200) ----" | tee -a run.log
          found=0
          for f in *.log; do
            if [ -f "$f" ] && [ "$f" != "run.log" ]; then
              found=1
              echo "----- $f -----" | tee -a run.log
              tail -n 200 "$f" | tee -a run.log || true
            fi
          done
          [ $found -eq 0 ] && echo "(no extra .log files)" | tee -a run.log

          echo "---- Verify recent Alpaca orders (Paper, last 5) ----" | tee -a run.log
          curl -s \
            -H "APCA-API-KEY-ID: ${APCA_API_KEY_ID}" \
            -H "APCA-API-SECRET-KEY: ${APCA_API_SECRET_KEY}" \
            "${PAPER_URL}/v2/orders?status=all&limit=5&direction=desc" > alpaca_orders_paper.json || echo "[]" > alpaca_orders_paper.json
          jq -r 'if type=="array" and length>0 then
                    .[] | "\(.submitted_at // "?")  \(.symbol // "?")  \(.side // "?")  qty=\(.qty // "?")  status=\(.status // "?")  id=\(.id // "?")"
                 else "[]" end' alpaca_orders_paper.json | tee -a run.log || true

          echo "---- Positions (Paper) ----" | tee -a run.log
          curl -s \
            -H "APCA-API-KEY-ID: ${APCA_API_KEY_ID}" \
            -H "APCA-API-SECRET-KEY: ${APCA_API_SECRET_KEY}" \
            "${PAPER_URL}/v2/positions" > alpaca_positions_paper.json || echo "[]" > alpaca_positions_paper.json
          jq -r 'if type=="array" and length>0 then
                    .[] | "\(.symbol) qty=\(.qty) avg_entry=\(.avg_entry_price)"
                 else "[]" end' alpaca_positions_paper.json | tee -a run.log || true

          echo "---- Activities FILL (Paper, recent) ----" | tee -a run.log
          curl -s \
            -H "APCA-API-KEY-ID: ${APCA_API_KEY_ID}" \
            -H "APCA-API-SECRET-KEY: ${APCA_API_SECRET_KEY}" \
            "${PAPER_URL}/v2/account/activities?activity_types=FILL&direction=desc&page_size=25" > activities_paper.json || echo "[]" > activities_paper.json
          jq -r 'if type=="array" and length>0 then
                    .[] | "\(.transaction_time // "?") \(.symbol // "?") \(.side // "?") qty=\(.qty // "?") price=\(.price // "?")"
                 else "[]" end' activities_paper.json | tee -a run.log || true

          # Échouer le job si le script a renvoyé un code d'erreur
          test "${PY_EXIT}" -eq 0

      - name: Upload artifacts (run.log + JSON + extra logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trader-paper-${{ github.run_id }}
          path: |
            run.log
            *.log
            alpaca_orders_paper.json
            alpaca_positions_paper.json
            activities_paper.json
          if-no-files-found: warn
          retention-days: 7

      - name: Commit & push logs/JSON
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add run.log *.log alpaca_orders_paper.json alpaca_positions_paper.json activities_paper.json || true
          git commit -m "Auto run $(date -u +%F)" || echo "No changes"
          git pull --rebase || true
          git push || true
