name: Portfolio

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: "30 20 * * 1-5"  # (ex) tous les jours ouvrés à 20:30 UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install -q --upgrade pip
            # fallback minimal si pas de requirements.txt
            pip install pandas
          fi

      - name: Run trading script (non-interactive)
        shell: bash
        run: |
          python -u trading_script.py \
            -f "Scripts and CSV Files/chatgpt_portfolio_update.csv" \
            -d "Scripts and CSV Files" \
            --non-interactive

      # (facultatif) Publier les fichiers mis à jour comme artefacts
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-outputs
          path: |
            Scripts and CSV Files/chatgpt_portfolio_update.csv
            Scripts and CSV Files/chatgpt_trade_log.csv
